id: opecha:P000403
initial_creation_type: ocr
source_metadata:
  id: bdr:W27598
  title: རྫོགས་ཆེན་ཁྲིད་ཡིག་ཡང་ཟབ་ཡིད་བཞིན་ནོར་བུ
  volume:
    9d82fdf40d1c45288ca6b53b5b66de97:
      image_group_id: I4468
      title: ''
      volume_number: 1
      total_pages: 322
  author: ''
ebook_metadata:
  title: རྫོགས་ཆེན་ཁྲིད་ཡིག་ཡང་ཟབ་ཡིད་བཞིན་ནོར་བུ
  author: ''
  sku: P000403
  cover: cover.jpg
  layers:
  - pagination
