id: P000403
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:38:08.260117
source_metadata:
  id: bdr:W27598
  title: རྫོགས་ཆེན་ཁྲིད་ཡིག་ཡང་ཟབ་ཡིད་བཞིན་ནོར་བུ
  author: ''
  volumes:
    9d82fdf40d1c45288ca6b53b5b66de97:
      image_group_id: I4468
      title: ''
      volume_number: 1
      total_pages: 322
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
