id: I07147C92
legacy_id: P000403
ocr_import_info:
  bdrc_scan_id: W27598
  source: bdrc
  ocr_info:
    timestamp: '2020-03-17T23:03:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:31:16.874825+00:00'
last_modified: 2022-09-02 15:31:38.556963
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27598
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27598
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫོགས་ཆེན་ཁྲིད་ཡིག་ཡང་ཟབ་ཡིད་བཞིན་ནོར་བུ།
  author: སྲས་འཕགས་མཆོག་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6768569490476098
  ocr_word_median_confidence_index: 0.7200000286102295
quality: null
bases:
  I4468:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4468
      total_pages: 322
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4468.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6768569490476098
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
